version: '3.8'
services:
  db_payment_engine:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=restapi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data_one

volumes:
  db:
    driver: local