ALTER TABLE users
DROP CONSTRAINT check_user_role;

ALTER TABLE users
ADD CONSTRAINT check_user_role CHECK
    (users.role IN ('ROLE_ADMIN', 'ROLE_POSTS', 'ROLE_USERS', 'ROLE_ALBUMS',
        'ROLE_TOTAL_OBSERVER', 'ROLE_POSTS_OBSERVER', 'ROLE_USERS_OBSERVER', 'ROLE_ALBUMS_OBSERVER'));
